### ISSUE TITLE
Update docker hub repository to v 1.4.0

### ISSUE THREAD

**Issue by kae** [hashicorp/docker-consul#108]
There is commit with update to 1.4.0 in this repository, but last push at https://hub.docker.com/_/consul/ is 25 days ago.

**Comment by eedwards-sk** [comment]
looks like we're waiting on this PR: https://github.com/docker-library/official-images/pull/5071

any maintainers around to follow up with this?

**Comment by kae** [comment]
@kyhavlov 
Is there an issue with update to PR requested in docker-library/official-images#5071 ?

**Comment by rboyer** [comment]
https://github.com/docker-library/official-images/pull/5071 Is now merged and versions `1.3.1` and `1.4.0` can now be pulled from docker hub.
