### ISSUE TITLE
Can't seem to get the api to work? Try this

### ISSUE THREAD

**Issue by thebenwaters** [hashicorp/docker-consul#16]
```
curl http://localhost:8500/v1/catalog/nodes
```

Connection refused???

Probably bound to the wrong network.

When running a client agent it kept binding to lo by default 

Set these bad boys in your environment variables and all of your problems will go away

CONSUL_BIND_INTERFACE=eth0
CONSUL_CLIENT_INTERFACE=eth0

(problems with docker-entrypoint.sh)

credit: @pauzed

**Comment by vgheri** [comment]
Hello, 
I added these two env variables and re-run `docker run consul` but I still get the same error `Failed to connect to localhost port 8500: Connection refused` .
Current configuration: Ubuntu on VirtualBox, Docker version 1.11.1, build 5604cbe, uname -a
Linux valerio-VirtualBox 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux


Any idea or hints?
Thanks,
Valerio

**Comment by slackpad** [comment]
https://github.com/hashicorp/docker-consul/pull/14 will bind to all interfaces by default for dev mode, which will fix this.
