### ISSUE TITLE
gpg: Can't check signature: No public key

### ISSUE THREAD

**Issue by lifeblood** [hashicorp/docker-consul#165]
'consul_1.6.2_linux_amd64.zip' saved
+ wget https://releases.hashicorp.com/consul/1.6.2/consul_1.6.2_SHA256SUMS
Connecting to releases.hashicorp.com (151.101.1.183:443)
saving to 'consul_1.6.2_SHA256SUMS'
consul_1.6.2_SHA256S 100% |********************************|  1148  0:00:00 ETA
'consul_1.6.2_SHA256SUMS' saved
+ wget https://releases.hashicorp.com/consul/1.6.2/consul_1.6.2_SHA256SUMS.sig
Connecting to releases.hashicorp.com (151.101.1.183:443)
saving to 'consul_1.6.2_SHA256SUMS.sig'
consul_1.6.2_SHA256S 100% |********************************|   543  0:00:00 ETA
'consul_1.6.2_SHA256SUMS.sig' saved
+ gpg --batch --verify consul_1.6.2_SHA256SUMS.sig consul_1.6.2_SHA256SUMS
gpg: Signature made Thu Apr 22 17:16:27 2021 UTC
gpg:                using RSA key B0B441097685B676
gpg: Can't check signature: No public key

**Comment by mkeeler** [comment]
@lifeblood Thanks for reporting this. It is related to a recent [security incident relating to the codecov breach](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512). 

We will be updating this repository in the very near future to download the new GPG key that all our release binaries have been resigned with.

**Comment by mkeeler** [comment]
The new GPG key has been merged.

**Comment by lifeblood** [comment]
too complicated
