### ISSUE TITLE
Can't use ping in script checks

### ISSUE THREAD

**Issue by kortatu** [hashicorp/docker-consul#17]
I migrated recently from progrium/consul image. In that image, consul is run as root user and all my ping script checks were working.
With this new image I get this:
`PING 192.168.0.36 (192.168.0.36): 56 data bytes`
`ping: permission denied (are you root?)`

I think ping is a very typical check script and it should work by default IMHO.

Is there a way to  make consul user to execute pings?
What about other script commands?

Thanks in advance.

**Comment by sbonar** [comment]
I realize this has been closed but I am still seeing this on Alpine 3.4 and 3.5.  Are you sure this is fixed??

**Comment by kortatu** [comment]
I still have the same problem in alpine 3.4. I created pull request #54 [https://github.com/hashicorp/docker-consul/pull/54](url) as an alternative solution.

**Comment by DexterHD** [comment]
I have same problem on Alpine 3.6 on last version of Consul (0.9.0)

**Comment by darkguy2008** [comment]
Wow, still having it in 2018...

**Comment by jakubgs** [comment]
Why is this issue closed? I cannot use `ping` inside of Consul docker container as a check becuase I'm getting this error about `permission denied`.

**Comment by mkeeler** [comment]
@jakubgs I will reopen this. I just tested myself and it currently does not work.

I think a simple solution is to just install the iputils package which replaces the busybox ping with a setuid one. Making the current /bin/ping setuid isn't a good idea as it makes the entire busybox binary setuid as /bin/ping is just a symlink.
