### ISSUE TITLE
Build official images for Consul 1.10.4, 1.9.11, and 1.8.17

### ISSUE THREAD

**Issue by ksmiley** [hashicorp/docker-consul#180]
There were three Consul releases yesterday (November 11) that included security updates, and it doesn't look like the Docker images for them are being built. I know it can take a few days for the images to make their way to Docker Hub because they have to go through the [official-images](https://github.com/docker-library/official-images/blob/master/library/consul) process, but as far as I can tell, the Dockerfile in this repository needs to be updated as the first step.

**Comment by ksmiley** [comment]
To clarify, I was looking at https://hub.docker.com/_/consul, but a coworker has pointed out that https://hub.docker.com/r/hashicorp/consul exists and has the latest tags. That page says the source repository is hashicorp/docker-consul, but since it has the latest releases, is it actually built from hashicorp/consul now? Should we be using that image instead?

I took a second look at some of the [docs that reference Docker](https://learn.hashicorp.com/collections/consul/docker), and it seems they're split between referencing `consul` or `hashicorp/consul`.

**Comment by eculver** [comment]
You are not wrong, thanks for bringing it to our attention! We are in the process of updating our release tooling and so there were a few hiccups. In any case, we will have the official image published shortly.

**Comment by eculver** [comment]
This was merged: https://github.com/docker-library/official-images/pull/11297. Official images are now updated. Thanks!
