### ISSUE TITLE
Could not find IP for interface

### ISSUE THREAD

**Issue by missedone** [hashicorp/docker-consul#23]
hi, folks

I was running docker inside of the vbox ubuntu 14.04 VM.
the consul docker image is the latest (0.6.4)

I got following error when start the consul container:
```
vagrant@vagrant:~$ docker run --rm --net=host --name=consul -e CONSUL_BIND_INTERFACE=192.168.59.104 consul
ip: can't find device '192.168.59.104'
Could not find IP for interface '192.168.59.104', exiting
```

IP `192.168.59.104` is the docker host IP (aka. the ubuntu VM IP)

if run `ip addr list` command in the consul container, I can see 4 interfaces:
```
# ip -o -4 addr list
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: eth0    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0\       valid_lft forever preferred_lft forever
3: eth1    inet 192.168.59.104/24 brd 192.168.59.255 scope global eth1\       valid_lft forever preferred_lft forever
4: docker0    inet 172.17.0.1/16 scope global docker0\       valid_lft forever preferred_lft forever
```

if run the command, got the error:
```
# ip -o -4 addr list 192.168.59.104
ip: can't find device '192.168.59.104'
```

the relate source code is here https://github.com/hashicorp/docker-consul/blob/master/0.6/docker-entrypoint.sh#L14

**Comment by missedone** [comment]
Closing this ticket.
I should pass ENV `CONSUL_BIND_ADDRESS` rather than `CONSUL_BIND_INTERFACE`

**Comment by ryansch** [comment]
@missedone Don't pass `CONSUL_BIND_ADDRESS` as that only exists as an internal implementation detail.

You should just pass the `-bind` option on the command line as binding to an address is supported natively by consul.

Example:
```sh
docker run --rm --net=host --name=consul consul agent -bind=192.168.59.104
```
