### ISSUE TITLE
Cannot launch official consul container on Mac (El Capitan)

### ISSUE THREAD

**Issue by yhzhao** [hashicorp/docker-consul#28]
I got the following error on my MAC after build the container successfully:

docker build -t test_consul . (The build is successful.)
docker run test_consul

Error response from daemon: Container command 'docker-entrypoint.sh' not found or does not exist.

I am running docker-machine version 0.4.1 (e2c88d6).

I tried to change the entry point pathname to /usr/bin, not working either.

**Comment by slackpad** [comment]
Hi @yhzhao I can't seem to reproduce this but that seems like a really old version of docker-machine. Have you tried upgrading that?

**Comment by slackpad** [comment]
Haven't heard any other reports and can't repro.
