### ISSUE TITLE
Adding runtime config

### ISSUE THREAD

**Issue by code-ape** [hashicorp/docker-consul#29]
Hi there,

I've run into an issue recently with deploying docker-consul with my use case and would like to offer to add a feature that address this if it's desired by hashicorp / this repo's maintainers.

**Issue:** environments that dynamically schedule containers (Mesos, Kubernetes, Rancher) are becoming common but dealing with state in them is hard. Using volumes to inject config's is not an option in these cases as the volume must either be distributed to every host or scheduling of the container must be limited to those which have the volume.

**Proposed feature:** many people have began using applications like [ContainerPilot](https://github.com/joyent/containerpilot) to do runtime configuration, upkeep, monitoring, and metrics (in fact ContainerPilot is often paired with Consul Templates to dynamically render config files). I will be creating a container that allows for runtime configuration via ContainerPilot which can be enacted by an environmental variable and thought that I would offer to contribute to the official Consul repo first before rolling my own.

Please let me know if this is something that would be accepted into this repo!

Thanks,
code-ape

**Comment by slackpad** [comment]
Hi @code-ape thanks for the heads up! Can you please describe the change in a little more detail? Would this involve integrating ContainerPilot into the official image, or adding some configuration options to help support it?

**Comment by code-ape** [comment]
@slackpad, thanks for the quick response! I'm currently imagining integrating ContainerPilot which would remain dormant unless an environmental variable, let's say `USE_CONTAINER_PILOT` for example, was set to true. Since I'm looking for everything to be stateless you could then specify either a file address (if volume mounting was an option) or HTTP(S) address to pull the containerpilot config from (if volume mounting wasn't an option). Though if there's an issue with this or you think there's a better option I'm open to ideas!

**Comment by slackpad** [comment]
Ah ok - this probably isn't a good fit for the official image since it should be limited to only running Consul, and folks that aren't using this wouldn't appreciate any extra image size that would come with it. This is probably better done as a separate project that's based on the official image and adds in support for ContainerPilot.
