### ISSUE TITLE
OpenSSL Vulnerability

### ISSUE THREAD

**Issue by clim** [hashicorp/docker-consul#31]
Hi Guys,

The official consul image in Docker Hub seems to have an OpenSSL vulnerability as reported in this page: https://hub.docker.com/r/library/consul/tags/v0.6.4/

--
Chris

**Comment by slackpad** [comment]
Hi @clim I'll take a look at updating that.

**Comment by slackpad** [comment]
Hi @clim that page is giving a 404 and I can't find any related info. Guessing that might be from Alpine, which I'm in the process of updating now. Core Consul shouldn't be using OpenSSL in any way.
