### ISSUE TITLE
Container exits instantly after starting with net parameters

### ISSUE THREAD

**Issue by ulfklose** [hashicorp/docker-consul#32]
I tried several ways to start the official image on my system:

    docker run -d consul

works just fine.

    docker run -d consul -P

doesn't. The container exits immediately. Enumerating the ports separately has the same effect. --net=host won't do the trick neither.

Docker logs says this:

    Invalid flags before the subcommand. If these flags are for
    the subcommand, please put them after the subcommand.

    usage: consul [--version] [--help] <command> [<args>]

    Available commands are:
        agent          Runs a Consul agent
        configtest     Validate config file
        event          Fire a new event
        exec           Executes a command on Consul nodes
        force-leave    Forces a member of the cluster to enter the "left" state
        info           Provides debugging information for operators
        join           Tell Consul agent to join cluster
        keygen         Generates a new encryption key
        keyring        Manages gossip layer encryption keys
        leave          Gracefully leaves the Consul cluster and shuts down
        lock           Execute a command holding a lock
        maint          Controls node or service maintenance mode
        members        Lists the members of a Consul cluster
        monitor        Stream logs from a Consul agent
        reload         Triggers the agent to reload configuration files
        rtt            Estimates network round trip time between nodes
        version        Prints the Consul version
        watch          Watch for changes in Consul

I'm on CentOS 7 with Docker 1.12.0.

**Comment by ryansch** [comment]
@ulfklose You're trying to pass the docker `-P` option to `consul` instead of to `docker`.  Try this:

`docker run -d -P consul`

**Comment by ulfklose** [comment]
Stupid me. Thanks for the hint, I'm good now. Please close the issue which isn't one 😉.

**Comment by slackpad** [comment]
Thanks @ryansch for fielding this one :-)

**Comment by ryansch** [comment]
😄
