### ISSUE TITLE
Reading configuration via mounting onto /consul/config doesn't work

### ISSUE THREAD

**Issue by oryband** [hashicorp/docker-consul#33]
I have resolved to setting `CONSUL_LOCAL_CONFIG` environment variable in the meanwhile. This looks like a bug.

**Comment by oryband** [comment]
my mistake. all appears to working properly. i just had to omit the `consul` from `consul agent` in the CMD part of the `docker run` command.

The examples show the opposite btw, and this is misleading.

**Comment by slackpad** [comment]
Reopening to check the docs and make sure they are correct.

**Comment by oryband** [comment]
Thanks!
