### ISSUE TITLE
About -bind=<external ip> -retry-join=<root agent ip>

### ISSUE THREAD

**Issue by zhengfc** [hashicorp/docker-consul#35]
Hi, I'm newer for consul. 
Can you tell me what is ```external ip``` and ```root agent ip```?

When I run the command:
```
$  docker run -d --net=host -e 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}' consul agent 
-bind=<external ip> -retry-join=<root agent ip>
``` 
just generate a docker container id and exit. 

I tried external ip: 
```
192.168.99.100   -- my docker default ip  
10.48.114.90     -- my computer ip  
172.17.0.2       -- dev-consul ip  
127.0.0.1
```
And the root agent ip, I just try
```
172.17.0.2
127.0.0.1
```
Thanks for you help and reply.

**Comment by slackpad** [comment]
Hi @zhengfc the "root_agent_ip" is the address of another Consul agent to join. The "external_ip" is the IP address that you want Consul to listen on and give out as the address of the node to the rest of the cluster. If you are just starting out with Consul, you may want to check out this tutorial for the basic mechanics - https://www.consul.io/intro/getting-started/install.html.
