### ISSUE TITLE
https://hub.docker.com/_/consul/ doesn't exist

### ISSUE THREAD

**Issue by cdrage** [hashicorp/docker-consul#4]
I'm assuming just waiting on docker hub for the LGTM?

**Comment by sethvargo** [comment]
Hi @cdrage 

Thank you for opening an issue. We are working through some changes the Docker team suggested before we can publish.

**Comment by slackpad** [comment]
Yep we opened the PR yesterday and are kicking off the review process - https://github.com/docker-library/official-images/pull/1436.
