### ISSUE TITLE
Why doesn't consul respect the name given to services

### ISSUE THREAD

**Issue by babatundebusari** [hashicorp/docker-consul#43]
I have noticed when i run services with docker, i provide them with names and yet when they register with consul, they have a different name

Why does consul not respect the names of containers/services?

**Comment by slackpad** [comment]
Hi @babatundebusari Consul doesn't have any native Docker registration functionality. This is probably a better question for whatever software you are using to do that (registrator?).

**Comment by babatundebusari** [comment]
@slackpad 
yes i used registrator
