### ISSUE TITLE
Conflicting Node ID when using Docker

### ISSUE THREAD

**Issue by rgruyters** [hashicorp/docker-consul#57]
When using Consul with Docker I noticed with 0.8.0 the following message appear:

`Failed to join 172.17.0.2: Member '330e1df099ea' has conflicting node ID 'a8a108a5-c071-49d0-84ef-b774af85c15f' with this agent's ID`

When I use version 0.7.5 this message doesn't appear. Although Node IDs are still the same.

**Comment by slackpad** [comment]
Hi @rgruyters please see https://github.com/hashicorp/consul/issues/2877 for some more information on that (closing this as a duplicate).

**Comment by shengnian** [comment]
when i use docker-compose build the consul, throw below error message: 
`[ERR] memberlist: Failed push/pull merge: Member 'consul-agent' has conflicting node ID 'ee3f3ae5-6f83-1689-5358-2734f0d8ff64' with this agent's ID from=172.19.0.4:44332`
version: consul:latest

and how to set node-id in docker-compose version 3. thanks.
