### ISSUE TITLE
Suggestion to add CONSUL_ADVERTISE as a parameter to containers; defaults to the IP listed in /etc/hosts

### ISSUE THREAD

**Issue by juliohm1978** [hashicorp/docker-consul#59]
As noted from the current [documentation](https://www.consul.io/docs/agent/options.html), the `-bind` and `-advertise` parameters are closely related. One can bind to all interfaces, but needs to advertise to a specific one. Otherwise, Consul will fail to startup.

When using Consul in a Docker Swarm spanning multiple hosts, containers will always have more than one interface, eth0, eth1, eth2, etc. These include the container IP, the swarm ingress bridge, loopback, etc. On top of that, container aliases and service names may not respond to the same IP as the one listed in `/etc/hosts`.

An obvious workaround is to bind Consul to all interfaces of the container using `-bind 0.0.0.0`, but this immediately conflicts with the `-advertise` parameter. When faced with multipe bind interfaces, we need to specify which one will be advertised. Finding out this value at runtime has showned to be a challenge.

There is an option to provide CONSUL_BIND_INTERFACE to the container, but by itself, this parameter is not as flexible as we exepct it to be.

Another option we found browsing the issue history here is to include calls to the YML compose file that returns the IP address of the desired interface. For exmaple:

```
command: ... -advertise='{{ GetInterfaceIP "eth2" }}'
```

However, given different swarm environments, the bind interface might change from eth0 to eth2, etc. The value of the bind interface is not portable across environments.

We found a way around this by replacing the image's original `docker-entrypoint.sh` with our own `custom-entrypoint.sh`. Our script expects and optional CONSUL_ADVERTISE variable to be present. When it's not available, it will deduce the advertise address from the container's `/etc/hosts`, which will have its public IP address.

```
#!/bin/sh

if [ "$CONSUL_ADVERTISE" == "" ]; then
  CONSUL_ADVERTISE="$(grep $(hostname) /etc/hosts | awk '{print $1}')"
fi
CONSUL_ADVERTISE="-advertise $CONSUL_ADVERTISE"

exec /usr/local/bin/docker-entrypoint.sh $@ $CONSUL_ADVERTISE
```

I'm leaving the suggestion to include this parameter as part of the image. Of course, always open to ideas to make this any better. I'm curious to understand any reason why this would not be a good idea.

Kind regards.

**Comment by isuftin** [comment]
@juliohm1978 Is there a reason that you wouldn't use the same mechanism to figure out the address as is already being done for CONSUL_BIND and CONSUL_CLIENT? 

`$(ip -o -4 addr list $CONSUL_BIND_INTERFACE | head -n1 | awk '{print $4}' | cut -d/ -f1)`

**Comment by vancluever** [comment]
Hi @juliohm1978, just wanted to put a note here as I have closed #64 - is it possible that you can get what you are looking for through the [go-sockaddr](https://github.com/hashicorp/go-sockaddr) example that was supplied in @slackpad's response in the PR, but kind of modified? Something like:

```
{{ GetDefaultInterfaces | include "type" "IPv4" | offset 0 | limit 1 | attr "address" }}
```

I realize that this is not the system hostname - I don't think there is a facility to check for the system hostname in go-sockaddr currently, but this should get the first IP address of the set of interfaces associated with the default route, and should hopefully be adjustable to something that should reliably get you the address you need to bind to when deploying in swarm.

Hope this helps!

**Comment by juliohm1978** [comment]
@vancluever 

I'm sure that a Go template, as suggested, will work just fine. I tried something similar before. My point is that deployment files, like `docker-compose.yml`, will become poluted with this logic. It seems to me that this code belongs inside the image itself.

Reading back, I think I wasn't clear with my huge explanation. I'm proposing a change to the entrypoint, which is standard a bash script. My custom `custom-entrypoint.sh` adds the logic for CONSUL_ADVERTISE and calls back the original `docker-entrypoint.sh` to continue.

**Comment by slackpad** [comment]
@juliohm1978 can you make use of the `CONSUL_LOCAL_CONFIG` environment variable for that use case? That lets you inject a bit of Consul config JSON right from the environment variable.

**Comment by juliohm1978** [comment]
@slackpad, thanks for the suggestion. Our Docker infrastructure is moving to Kubernetes and we haven't had the chance to try other configurations. The current workaround we had in place is working perfectly.

Will reopen in the future if we run into problems.
