### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by stanzheng** [hashicorp/docker-consul#65]
The only tagged versions are `0.9` and `latest` on dockerhub

should previous tagged versions also be available? 

https://hub.docker.com/_/consul/

**Comment by slackpad** [comment]
Hi @stanzheng the Docker folks at one point encouraged us to keep the list trimmed to just versions we are supporting, so those are the only ones shown on the hub, but you should still be able to pull the older tags which don't go away.

**Comment by stanzheng** [comment]
ah alright thanks!

**Comment by hraban** [comment]
I just tried:

```
$ docker run --rm consul:0.9 whoami
Unable to find image 'consul:0.9' locally
docker: Error response from daemon: manifest for consul:0.9 not found.
See 'docker run --help'.
```

Can I depend on old consul versions hanging around? I'm trying to use them in a dockerized integration test suite for a micro services arch and it's a bit stressful not to be able to pin the version, having to watch consul CLI updates etc for the whole integration test suite to work. Is there a recommended solution for this? Or am I missing an obvious hack?

**Comment by slackpad** [comment]
Hi @hraban you need to put the full version number in there for the tag - `docker run --rm consul:0.9.0 whoami` works.

**Comment by hraban** [comment]
super duper, thanks a p.. whooper.
