### ISSUE TITLE
Multi-arch docker images for consul

### ISSUE THREAD

**Issue by vaibhavsood** [hashicorp/docker-consul#67]
Hi, I'm looking to enable docker containers for packages like consul for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum.

The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, as mentioned there they recommend having a single dockerfile with swithches for arch-specific changes, want to understand if ppc64le additions would be accepted to the dockerfile here (can raise a PR) and if the ppc64le image creation process can be initiated subsequently under docker-library/official-images (would mostly need changes to the metadata file https://github.com/docker-library/official-images/blob/master/library/consul)

Thanks!

**Comment by vielmetti** [comment]
I'm in the same boat, requesting an arm64v8 (64-bit Arm) version of Consul for NFV use.

**Comment by vielmetti** [comment]
Alerting @tianon to see if there's any insight to share.

**Comment by mterron** [comment]
I don't work for Hashicorp @vielmetti  so can't comment on this, sorry.
Consul is built for arm64 [https://releases.hashicorp.com/consul/1.0.1/consul_1.0.1_linux_arm64.zip](https://releases.hashicorp.com/consul/1.0.1/consul_1.0.1_linux_arm64.zip) though and you could build your own Docker images.

**Comment by vielmetti** [comment]
Alerting @slackpad as well.

**Comment by tianon** [comment]
From the official images perspective, @vaibhavsood already linked to the same file I would. 👍 

I'm also happy to help implement or test any of these changes.

**Comment by seffyroff** [comment]
I also just looked at this, and comparing to a few other repos (HAProxy) the upstream library and manifest files seem to be generated artifacts at buildtime from the [stackbrew process](https://github.com/docker-library/haproxy/blob/1fa9d01682376087032e856c0a8c319f97c2ebec/generate-stackbrew-library.sh).

As there's currently no docker-library repo for Consul, this would be the place to start, I imagine.

In the meantime I built my own :)

**Comment by slackpad** [comment]
We don't have plans to do this ourselves but we'd welcome a PR that adds this, as long as it would add too much complexity to the current release process.

**Comment by tianon** [comment]
Done deal!  Happy to adjust https://github.com/hashicorp/docker-consul/pull/82 as much as desired. :heart:

**Comment by vielmetti** [comment]
We should expect this to be visible in the 1.0.8 timeframe, correct?

**Comment by tianon** [comment]
This is something that should now be reasonably safe to add anytime by updating `GitCommit:` and adding `Architectures: amd64, i386, arm32v6, arm64v8` to `library/consul` in https://github.com/docker-library/official-images. :+1:
