### ISSUE TITLE
consul:1.0.0 reports 0.9.3

### ISSUE THREAD

**Issue by NoumanSaleem** [hashicorp/docker-consul#68]
```
docker run --rm consul:1.0.0 -v
> Consul v0.9.3
```

**Comment by slackpad** [comment]
Hi @NoumanSaleem I pinged the Docker folks to see what's going on there.

**Comment by slackpad** [comment]
Looks like something got kicked and the tags are working now if you pull them. https://github.com/docker-library/official-images/pull/3591 should prevent this in the future. Thanks for spotting this @NoumanSaleem!

**Comment by NoumanSaleem** [comment]
Thank you @slackpad !
