### ISSUE TITLE
data_dir cannot be empty

### ISSUE THREAD

**Issue by kostonstyle** [hashicorp/docker-consul#70]
Hi all 
I created a Dockerfile that looks as follow:

```
FROM consul

ENTRYPOINT ["consul", "agent"]

COPY config-file.json /consul/config

```
The config( config-file.json) file that looks as follow:

```
{
  "datacenter": "microservices",
  "data_dir": "/tmp/consul",
  "log_level": "INFO",
  "disable_host_node_id" : true, 
  "server": true,
  "bootstrap_expect" : 2,
  "client_addr": "0.0.0.0",
  "ui": true,
  "bind_addr": "192.168.70.20",  
  "watches": [
    {
        "type": "checks",
        "handler": "/usr/bin/health-check-handler.sh"
    }
  ],
  "telemetry": {
     "statsite_address": "127.0.0.1:2180"
  }
}
```
then run the container and got following:

```
dockerizer@docker1:~/consul$ docker run --rm -ti --network=host servery
==> data_dir cannot be empty
```  
What am I doing wrong?  

Thanks

**Comment by kostonstyle** [comment]
Now change Dockerfile to:

```
FROM consul

COPY config-file.json /consul/config

ENTRYPOINT ["consul", "agent, "-config-file=/consul/config/config-file.json"]
```
I've got following error:

```
dockerizer@docker1:~/consul$ docker run --rm -ti --network=host servery
/bin/sh: syntax error: unterminated quoted string
```

Thanks

**Comment by natemara** [comment]
It looks like on your entrypoint line there is an error:

    ENTRYPOINT ["consul", "agent, "-config-file=/consul/config/config-file.json"]
                                ^

You're missing the closing quote after `agent`.

**Comment by thunderbird86** [comment]
Have the same problem without docker 
```
# consul -v
Consul v1.0.1
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
# consul agent
==> data_dir cannot be empty
```

There is config
```
{
    "client_addr": "127.0.0.1",
    "data_dir": "/var/lib/consul",
    "datacenter": "dc1",
    "leave_on_terminate": true,
    "performance": {
        "raft_multiplier": 5
    },
    "retry_join": [
        "provider=aws tag_key=consul_join tag_value=env-name"
    ]
}
```
and here is validate
```
#consul validate /etc/consul.conf
Config validation failed: data_dir cannot be empty
```

**Comment by danlsgiga** [comment]
Same here running consul 1.0.1.
data_dir cannot be empty when it is clearly set in the config

**Comment by slackpad** [comment]
If you just run `consul agent` without any more arguments it won't find your config file in /etc/consul.conf, you'll need to run `consul agent -config-file=/etc/consul.json`. If I run `consul validate` on the JSON above it validates. Hope that helps!

**Comment by danlsgiga** [comment]
Thanks @slackpad, that fixed the issue!

**Comment by jianhaiqing** [comment]
consul validate /etc/consul.d  /etc/consul.json && consul reload

**Comment by bob-baohai** [comment]
very good!

**Comment by zenina** [comment]
I was able to workaround this issue by passing 

`--data-dir /path/to/datadir `
in my upstart script/startup options. I presume consul is not parsing the option out of the config file correctly. 

`consul agent -data-dir /var/consul -config-dir /etc/consul.d/client`
