### ISSUE TITLE
gpg: keyserver receive failed: No keyserver available

### ISSUE THREAD

**Issue by jimmyraywv** [hashicorp/docker-consul#71]
In OSX with Docker Version 17.09.0-ce-mac35 (19611)

`gpg: directory '/root/.gnupg' created
gpg: new configuration file '/root/.gnupg/dirmngr.conf' created
gpg: new configuration file '/root/.gnupg/gpg.conf' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: No keyserver available`

I have had to remove all the __gpg__ commands to make the build work.  And I have had to replace all the __wget__ calls with __curl -O__ . All other calls via the proxy works fine.

**Comment by slackpad** [comment]
Hi @jimmyraywv the key servers can sometimes not be available temporarily, or you may need to configure a new one. This isn't something we have control over, though.
