### ISSUE TITLE
Is there possible to set cert_file, key_file, and ca_file without creation own image

### ISSUE THREAD

**Issue by vvchik** [hashicorp/docker-consul#78]
I am trying to avoid binding a volume to /consul/config 
And to avoid composing a new image and adding files. 

Is it possible to encode Certificates and Key as CMD attributes or ENV variables?

**Comment by slackpad** [comment]
Hi @vvchik this is currently not possible, unfortunately. They have to be read from files and can't be supplied in-line via configuration.
