### ISSUE TITLE
should each app container has its own consul agent, or all the app containers share one consul agent container?

### ISSUE THREAD

**Issue by LittleShrimp1987** [hashicorp/docker-consul#79]
should each app container also has its own consul agent in it, or all the app containers share one consul agent container?

**Comment by slackpad** [comment]
Consul agents are tied to a specific host, so it's generally better to run one agent per host and have all the app containers use that one agent. This will make things clean from Consul's perspective when it detects a problem with that host, and it will avoid multiplying gossip traffic by running multiple agents on one host when a single agent will do. Hope that helps!

**Comment by LittleShrimp1987** [comment]
thanks for you answer.

**Comment by LittleShrimp1987** [comment]
I want to deploy my consul-based spring boot application in k8s, the best way is deploy consul as daemonset in each k8s node and the node's pods share consul agent. BUT so far, as I know, there is no hostIP env exposed to pod. I want to know if anyone has best practice to solve my problem?

**Comment by tuananhb94** [comment]
@LittleShrimp1987 , oh did you solve the problem you mention ?
